# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 22:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortenurls', '0002_url_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlVisits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('visits', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='url',
            name='original_url',
            field=models.CharField(max_length=255, validators=[django.core.validators.URLValidator]),
        ),
        migrations.AddField(
            model_name='urlvisits',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortenurls.Url'),
        ),
    ]
