# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortenurls', '0004_urlvisits_last_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='no_of_requests',
        ),
    ]
