# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortenurls', '0005_remove_url_no_of_requests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlvisits',
            old_name='last_visit',
            new_name='last_visit_at',
        ),
        migrations.AddField(
            model_name='urlvisits',
            name='last_visit_from',
            field=models.CharField(default=django.utils.timezone.now, max_length=39),
            preserve_default=False,
        ),
    ]
