# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortenurls', '0006_auto_20180402_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlVisitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_address', models.CharField(max_length=39)),
                ('user_agent', models.CharField(max_length=255)),
                ('visits', models.IntegerField(default=0)),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('url_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortenurls.UrlVisits')),
            ],
        ),
        migrations.AddField(
            model_name='url',
            name='last_visit_from',
            field=models.CharField(default=django.utils.timezone.now, max_length=39),
            preserve_default=False,
        ),
    ]
