# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenurls', '0007_auto_20180402_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='last_visit_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
