# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenurls', '0008_url_last_visit_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlvisits',
            name='last_visit_at',
            field=models.DateTimeField(),
        ),
    ]
