# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenurls', '0009_auto_20180404_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlvisits',
            name='last_visit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
