# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenurls', '0010_auto_20180404_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlvisitors',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
