# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenurls', '0011_auto_20180404_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='last_visit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
